Overview.bs
Overview.html

- Generalizes the structure so it can use branch factors other than the previously hardcoded 8. Using 4 is recommended for the general case, but I left open the option for encoders to chose factors other than 4.
- Added interval encoding using a 0 value node. My current thinking is that this does not add any additional size to the encoding even if it's not used if we recommend that the encoder should encode intervals inside of CompressedSet. So we should at least include it in the spec so that an advanced encoder could make use of it if desired.
- Adds an example that covers a branch factor of 4, with an encoded interval.

Updated sparse bit set specification section.

---

Overview.bs
Overview.html

- Remove the response_type field from responses. This is now inferred by the client based on which fields are set/unset.
- Unify handling of patch and rebase in the client (treats rebase as a patch against a zero length file).
- Adds specification for expected server behaviour. This is intentionally very minimal to give server implementations plenty of flexibility.

Simplifies the client specification and adds server specification for patch subset

---

Overview.bs
Overview.html
RangeRequest.html

Similar to codepoints this adds an axis space have and axis space needed to the request. This allows a client to get a subset of the font with a reduced axis space and then later on expand the axis space via a patch.

Add the capability for a client to incrementally transfer vf axis space

---

Overview.bs
Overview.html

Needed so that the client can determine if the response is patch subset or a regular font file on the first response.

Add 4 byte magic number to PatchResponse.

---

Overview.bs
Overview.html

This allows for a client to specify things like I want weight 300 and weight 700 without being forced to ask for the entire interval from 300 to 700.

Update AxisSpace to use a list of intervals for each tag.

---

Overview.bs
Overview.html

Mention the need to preserve optional features from the original font.
#45  and #41
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/IFT/pull/53.html" title="Last updated on Nov 26, 2021, 5:28 PM UTC (11640e7)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/IFT/53/d12e38b...11640e7.html" title="Last updated on Nov 26, 2021, 5:28 PM UTC (11640e7)">Diff</a>

Reword font subset definition

---

Overview.bs
Overview.html

As discussed in the last call and in #49 don't include a mechanism for the client to report it's connection speed. Move the note about requesting additional characters on slower connections into the client section.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/IFT/pull/64.html" title="Last updated on Dec 13, 2021, 6:26 PM UTC (8ecd618)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/IFT/64/f1f7516...8ecd618.html" title="Last updated on Dec 13, 2021, 6:26 PM UTC (8ecd618)">Diff</a>

Remove connection speed field.

---

Overview.bs
Overview.html

Adds several examples of marking conformance statements with <span> tags. This is being done so that these statements can be linked to from the conformance tests.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/IFT/pull/55.html" title="Last updated on Dec 13, 2021, 7:08 PM UTC (509d878)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/IFT/55/79ee213...509d878.html" title="Last updated on Dec 13, 2021, 7:08 PM UTC (509d878)">Diff</a>

Add examples of marking up conformance statements

---

Overview.bs
Overview.html

Additionally:
- Link directly to request parameter definitions.
- Specify cors mode must be "cors"
For #69.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/IFT/pull/70.html" title="Last updated on Dec 16, 2021, 6:09 PM UTC (c323575)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/IFT/70/800a18b...c323575.html" title="Last updated on Dec 16, 2021, 6:09 PM UTC (c323575)">Diff</a>

Clarify that unspecified request/url parameters defer to regular font loading behaviour

---

Makefile
Overview.bs
Overview.html

For the most part moves text fom the later intro section up to the patch subset overview section.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/IFT/pull/77.html" title="Last updated on Mar 8, 2022, 9:16 PM UTC (e729721)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/IFT/77/21043b6...e729721.html" title="Last updated on Mar 8, 2022, 9:16 PM UTC (e729721)">Diff</a>

Expand patch subset overview section. 

---

Overview.bs
Overview.html

Ensure that next /TR publication links to both FPWD
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/IFT/pull/84.html" title="Last updated on Mar 8, 2022, 8:24 PM UTC (7629163)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/IFT/84/21043b6...7629163.html" title="Last updated on Mar 8, 2022, 8:24 PM UTC (7629163)">Diff</a>

Link publication history, both previous versions

---

Overview.bs
Overview.html

A couple of changes:
- Remove branch factor 16, and replace with branch factor 2. Our more recent simulations show branch factor 2 is useful to have.
- Change depth to be 5 bits which is sufficient to encode all 32 bit integers in all available branch factors. This leaves 1 reserved bit we can have for future use.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/IFT/pull/85.html" title="Last updated on Mar 16, 2022, 12:37 AM UTC (8bab773)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/IFT/85/2a8c0d6...8bab773.html" title="Last updated on Mar 16, 2022, 12:37 AM UTC (8bab773)">Diff</a>

Update sparse bit set details.

---

Overview.bs
Overview.html

Adds tags used by https://github.com/w3c/ift-server-tests/pull/7
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/IFT/pull/86.html" title="Last updated on Mar 26, 2022, 12:51 AM UTC (b41b3a6)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/IFT/86/69391ea...b41b3a6.html" title="Last updated on Mar 26, 2022, 12:51 AM UTC (b41b3a6)">Diff</a>

Tags some additional server conformance requirements.

---

Overview.bs
Overview.html

Change to have these font derived fields sent whenever the server sees a mismatch between the client reported original font checksum and the servers original font checksum. This allows the fields to be updated in the client's state during a font version upgrade. Such as when a server is patching a client to a new version of the original font.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/IFT/pull/97.html" title="Last updated on Jun 13, 2022, 9:26 PM UTC (aa8dc8f)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/IFT/97/9fc60c1...aa8dc8f.html" title="Last updated on Jun 13, 2022, 9:26 PM UTC (aa8dc8f)">Diff</a>

Re-work when original_font_checksum, original_features, original_axis_space, and codepoint_ordering are sent.

---

Overview.bs
Overview.html

This PR does a couple of things:
- Reword the extend a font subset section to have explicit inputs and outputs. Adds the HTTP fetch algorithm as an input (see: #63, https://github.com/w3c/IFT/issues/69#issuecomment-995236057)
- Adds new section "Load a Font in a User Agent with a HTTP Cache" which provides a suggested algorithm for how to interact with and save client state into the HTTP cache. Addresses #72
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/IFT/pull/98.html" title="Last updated on Jun 13, 2022, 9:34 PM UTC (3791bd3)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/IFT/98/a29c9f1...3791bd3.html" title="Last updated on Jun 13, 2022, 9:34 PM UTC (3791bd3)">Diff</a>

Provide guidance on how a client may choose to integrate with it's HTTP cache.

---

Overview.bs
Overview.html

Fixes #28.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/IFT/pull/100.html" title="Last updated on Jun 16, 2022, 11:54 PM UTC (67d7022)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/IFT/100/693d133...67d7022.html" title="Last updated on Jun 16, 2022, 11:54 PM UTC (67d7022)">Diff</a>

Add fragment_id field to PatchRequest for specifying a font within a collection.

---

Overview.bs
Overview.html

For #62
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/IFT/pull/99.html" title="Last updated on Jun 16, 2022, 11:14 PM UTC (317e4ca)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/IFT/99/693d133...317e4ca.html" title="Last updated on Jun 16, 2022, 11:14 PM UTC (317e4ca)">Diff</a>

In the privacy section that checksums are only used in patch subset.

---

Overview.bs
Overview.html

For example for range request link to the specific range request section within rfc9110.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/IFT/pull/102.html" title="Last updated on Jun 22, 2022, 6:38 PM UTC (17687d7)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/IFT/102/497c2d4...17687d7.html" title="Last updated on Jun 22, 2022, 6:38 PM UTC (17687d7)">Diff</a>

Make HTTP RFC references more specific.

---

Overview.bs
Overview.html

Fixes #105.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/IFT/pull/111.html" title="Last updated on Jul 8, 2022, 8:47 PM UTC (54ec9bd)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/IFT/111/b5322b7...54ec9bd.html" title="Last updated on Jul 8, 2022, 8:47 PM UTC (54ec9bd)">Diff</a>

Shrink Integer primitive range to match that of an int64_t.

---

Overview.bs
Overview.html

This introduces three css font tech keywords to aid method selection:
- incremental-patch: tells client to use patch subset
- incremental-range: tells client to use range request
- incremental-auto: tells client to use the existing method negotiation mechanism.
Additionally the negotiation mechanism has been revised to use a GET + Header in the initial request instead of GET + a URL query parameter. This addresses feedback about the use of a URL query parameter.
This is based on the findings of [Revisting Method Negotiation in Incremental Transfer](https://docs.google.com/document/d/1IcPg4o5k4OOmfLCfa1z2wQl6MD-kPBrahtcb4r-97ZU/edit?usp=sharing&resourcekey=0-9WtXKj_y4uihiB7K740xMQ)
Marking as draft, pending discussions with CSS wg about changing the incremental font tech keyword.
This will …

Revise method selection and negotiation.

---

Overview.bs
Overview.html

Fixes #57 also bumps shared brotli spec version so it's no longer pointing at an expired one for #101.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/IFT/pull/126.html" title="Last updated on Nov 9, 2022, 6:55 PM UTC (04f6f72)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/IFT/126/bc5b5fd...04f6f72.html" title="Last updated on Nov 9, 2022, 6:55 PM UTC (04f6f72)">Diff</a>

Add a 'should' requirement to have client support both methods.

---

Overview.bs
Overview.html

Additionally applies definition markup to the font subset section, data types, object fields, and client state. This is the first step in addressing #106.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/IFT/pull/130.html" title="Last updated on Nov 11, 2022, 12:53 AM UTC (ba1a361)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/IFT/130/d1f0a51...ba1a361.html" title="Last updated on Nov 11, 2022, 12:53 AM UTC (ba1a361)">Diff</a>

Update "Extend the font subset" to use algorithm markup.

---

Overview.bs
Overview.html

Updates the "Handling Server Response" and "Load a Font  in a User Agent with a HTTP Cache" sections to use algorithm markup. Also merges the client side checksum mismatch and and the error handling sections to be inline in the handling server response section.
Fixes #106
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/IFT/pull/131.html" title="Last updated on Nov 14, 2022, 11:49 PM UTC (9f68756)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/IFT/131/992c405...9f68756.html" title="Last updated on Nov 14, 2022, 11:49 PM UTC (9f68756)">Diff</a>

Update remaining algorithms to use markup

---

Overview.bs
Overview.html

Both of these checksums are not strictly required. The ordering checksum can be computed by the client and patched checksum duplicates the purpose of checksums inside the font.
Fixes #121
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/IFT/pull/132.html" title="Last updated on Nov 17, 2022, 11:27 PM UTC (7cf4ac6)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/IFT/132/5d25f86...7cf4ac6.html" title="Last updated on Nov 17, 2022, 11:27 PM UTC (7cf4ac6)">Diff</a>

Remove ordering and patched checksum from response.

---

Overview.bs
Overview.html

Specifically we only use section 3.2 from the shared brotli spec, so link to that directly.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/IFT/pull/134.html" title="Last updated on Nov 22, 2022, 11:51 PM UTC (b6ccbe9)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/IFT/134/7f5e82e...b6ccbe9.html" title="Last updated on Nov 22, 2022, 11:51 PM UTC (b6ccbe9)">Diff</a>

Clarify how brotli patches are made.

---

Overview.bs
Overview.html

Adds a custom table to the font subset which houses client state. See: https://docs.google.com/document/d/1uws2h-48FRxFQPXN8ZHlmWRl35wRsCREUi_vr7-m9cY/edit?usp=sharing for more details.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/IFT/pull/136.html" title="Last updated on Mar 1, 2023, 8:42 PM UTC (e15068a)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/IFT/136/4886f2d...e15068a.html" title="Last updated on Mar 1, 2023, 8:42 PM UTC (e15068a)">Diff</a>

Make client state part of the font file.

---

Overview.bs
Overview.html

For patch subset, instead of responding with a PatchResponse object, respond directly with the extended subset encoded using one of the patch formats. Since most of the patch response has been moved to the client state table that is part of the font file, the PatchResponse wrapper no longer provides any real value and can be eliminated. Content encoding negotiation is moved from a field in PatchResponse into the standard accept-encoding/content-encoding headers. Unrecognized codepoint ordering error handling is changed to have the server just send the full file instead of having client resend the request.
Overall this simplifies the specification without any real loss of functionality and better utilizes existing mechanisms (ie. content-encoding)
***
<a …

Remove PatchResponse from the specification

---

Overview.bs
Overview.html
RangeRequest.bs
RangeRequest.html

Bikeshed no longer supports the section name references. See: #143.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/IFT/pull/144.html" title="Last updated on Apr 12, 2023, 8:10 PM UTC (27f88d4)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/IFT/144/3559830...27f88d4.html" title="Last updated on Apr 12, 2023, 8:10 PM UTC (27f88d4)">Diff</a>

Update rfc9110 and rfc9111 to use section references.

---

Overview.bs
Overview.html
RangeRequest.html

This is used to prevent a malicious font server from continuously varying the codepoints which are present in the font subset in order to gain information about which codepoints are present in content.
Also fix a bunch of typos/spelling.
Part of the fix for #42 and #50
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/IFT/pull/146.html" title="Last updated on Jun 19, 2023, 7:05 PM UTC (c2e9b83)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/IFT/146/d0d75bf...c2e9b83.html" title="Last updated on Jun 19, 2023, 7:05 PM UTC (c2e9b83)">Diff</a>

Add a mechanism to client state that prevents re-requesting codepoints

---

Makefile
Overview.bs
Overview.html
RangeRequest.html
obfuscation-blocks.html
obfuscation_blocks_to_html.py

This adds a grouping mechanism to the patch subset client specification. This requires that for certain blocks of codepoints those codepoints always be requested in groups with a minimum size.
The impact of grouping on privacy was simulated here: https://github.com/w3c/PFE-analysis/blob/main/results/noise_simulations.md
There's still a couple of open questions we probably want to discuss with the WG before merging this:
1. What is an appropriate minimum group size? for now I've chosen 7 based on the simulation results.
2. Which codepoints specifically should we add to the list of codepoints to be grouped? Currently I only include all of the CJK ideograph blocks, but not any of the other CJK blocks (eg. punctuation, compatibility points, and so on)
Addresses: #42 and #50
***
<a …

Add codepoint obfuscation via grouping to the patch subset specification.

---

Overview.bs
Overview.html
feature-registry.csv
registry_to_html.py

'default included' features can now be omitted from the set by including the ID associated with that feature. This allows the client to fully customize the feature set if the list of default included features does not match what the client's shaper is expected to require for it's current content. For example the default included 'vert' feature could be omitted if no vertical layout is being done.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/IFT/pull/149.html" title="Last updated on Sep 7, 2023, 5:17 PM UTC (77059cd)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/IFT/149/9568adc...77059cd.html" title="Last updated on Sep 7, 2023, 5:17 PM UTC (77059cd)">Diff</a>

Revamp the FeatureTagSet encoding scheme.

---

Overview.bs
Overview.html
RangeRequest.bs
RangeRequest.html

We eventually switched to the `https://httpwg.org/specs/` versions for RFC9110, RFC9111 and RFC9112 in the cross-references database, because they are more readable.
Unfortunately, this means that references to sections in these specs need to be updated again, as was done in #144. This update uses the new (and in theory now stable) fragment identifiers.
***
<a href="https://pr-preview.s3.amazonaws.com/tidoust/IFT/pull/154.html" title="Last updated on Nov 24, 2023, 3:15 PM UTC (643d5ab)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/IFT/154/01037d2...tidoust:643d5ab.html" title="Last updated on Nov 24, 2023, 3:15 PM UTC (643d5ab)">Diff</a>

Update references to RFC9110, RFC9111 and RFC9112

---

Overview.bs
Overview.html

Adds spec text for the missing format 2 patch map section. Format 2 provides a general purpose mapping that supports design spaces and overlapping mapping entries.
Preview can be seen here: https://garretrieger.github.io/IFT/Overview.html#patch-map-format-2
***
<a href="https://pr-preview.s3.amazonaws.com/garretrieger/IFT/pull/159.html" title="Last updated on Mar 7, 2024, 10:52 PM UTC (9b8fd31)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/IFT/159/bec0db4...garretrieger:9b8fd31.html" title="Last updated on Mar 7, 2024, 10:52 PM UTC (9b8fd31)">Diff</a>

Add specification for the Format 2 Patch Map

---

Overview.bs
Overview.html

This defines patch URI's as URI references which may be relative. Relative references use the containing incremental font URI as the base URI.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/IFT/pull/162.html" title="Last updated on Apr 9, 2024, 10:38 PM UTC (5ee2cea)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/IFT/162/25b4515...5ee2cea.html" title="Last updated on Apr 9, 2024, 10:38 PM UTC (5ee2cea)">Diff</a>

Add text for the "Load a Patch File" algorithm.

---

Overview.bs
Overview.html

- Further clarifies some of the text in the encoder section.
- Adds more of the text for encoder guidance.
- Cleans up a bunch of TODO's throughout.
- Change from "shared brotli" to "brotli"
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/IFT/pull/161.html" title="Last updated on Apr 12, 2024, 10:11 PM UTC (d90c786)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/IFT/161/545a4a1...d90c786.html" title="Last updated on Apr 12, 2024, 10:11 PM UTC (d90c786)">Diff</a>

Updates to the encoder section + TODO cleanup

---

Overview.bs
Overview.html

This makes them consistent with the glyph keyed format.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/IFT/pull/164.html" title="Last updated on Apr 13, 2024, 12:51 AM UTC (653e523)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/IFT/164/a0c1406...653e523.html" title="Last updated on Apr 13, 2024, 12:51 AM UTC (653e523)">Diff</a>

Add reserved and length fields to the two Brotli patch formats.

---

Overview.bs
Overview.html

Adds the ability to optionally assign entries in a format 2 table opaque string id's (instead of numeric ids).
Also widen several of the format 2 fields:
- entryCount (and associated copyIndices) uint16 -> uint24.
- designSpaceCount uint8 -> uint16 to match the max number of axes in fvar.
- entryIdDelta int16 -> int24 to allow for bigger gaps, and a higher maximum id value.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/IFT/pull/165.html" title="Last updated on Apr 18, 2024, 9:47 PM UTC (84496c3)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/IFT/165/6f5387f...84496c3.html" title="Last updated on Apr 18, 2024, 9:47 PM UTC (84496c3)">Diff</a>

Add optional ID string mapping to format 2.

---

Overview.bs
Overview.html

This reorders several of the top level sections in order to make the specification easier to understand by an unfamiliar reader:
1. Move the 'Extending a Font Subset' section to before the patch map and patch formats section. This introduces the process which utilizes patch maps and patches before getting into the minute details of those.
2. In the common definitions section, add basic summaries of patch maps and patches. This is needed to introduce the basics on these concept before they are used in the 'Extending a Font Subset' algorithm.
3. Move the 'URI Templates' from the common definitions into the patch map table section, which is the only section that references it.
4. Move the 'Patch Invalidations' section from the patch map section and into the 'Extending a Font Subset Section' …

Major Reorganization of Spec Sections.

---

Overview.bs
Overview.html

As discussed in #167
Not sure the advice about bytes to encode is sufficient or clear enough. That's supposed to match the advice on omitting leading hex zeros, but the issue is more complicated with base32hex because you wind up with some leading zeros anyway.
***
<a href="https://pr-preview.s3.amazonaws.com/skef/IFT/pull/169.html" title="Last updated on May 12, 2024, 7:54 AM UTC (f74bc6e)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/IFT/169/fbabe92...skef:f74bc6e.html" title="Last updated on May 12, 2024, 7:54 AM UTC (f74bc6e)">Diff</a>

Switch ID encoding to base32hex

---

Overview.bs
Overview.html

As discussed in #177 . 
I think we settled on "format number" instead of "ID a while back to reduce the overloading of "identifier" in the spec. So this updates the column heading to reflect that. (If I'm wrong I can back that out.)
Closes #177
***
<a href="https://pr-preview.s3.amazonaws.com/skef/IFT/pull/179.html" title="Last updated on May 22, 2024, 9:10 AM UTC (684925c)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/IFT/179/bcb93fd...skef:684925c.html" title="Last updated on May 22, 2024, 9:10 AM UTC (684925c)">Diff</a>

Remove (non-per-table) brotli partial invalidation patch format number

---

Overview.bs
Overview.html

I've introduced two mechanisms to limit the number of iterations that can be made in the extension algorithm (to prevent malformed/bad fonts from causing an excessive or infinite number of iterations):
1. Added text to prevent re-loading the same patch url multiple times (this prevents a case where a patch that does nothing is applied over and over again).
2. Introduced iteration limits:
- Limited the number of partial/full invalidation patch loads to 100, this limit is lower because these patches have to be loaded and applied serially.
- Limited the total number of patch applications of any type to 2000. This limit is higher since No Invalidation patches will loaded and applied in parallel.
The specific numeric limits are a first pass and I'm open to discussion on what would be good …

First pass at adding iteration limits to the extension algorithm.

---

Overview.bs
Overview.html

Also expand the load a patch description to mention that the CORS settings from the parent font should be used on the patch requests. This ensures patch requests will follow the same CORS protections that fonts are subject too.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/IFT/pull/180.html" title="Last updated on Jun 4, 2024, 4:51 PM UTC (89754b7)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/IFT/180/77451a7...89754b7.html" title="Last updated on Jun 4, 2024, 4:51 PM UTC (89754b7)">Diff</a>

Note the mitigations for limiting the number of requests in security considerations.

---

Overview.bs
Overview.html

For #183
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/IFT/pull/185.html" title="Last updated on Jun 18, 2024, 6:23 PM UTC (2894d16)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/IFT/185/0f7eb6e...2894d16.html" title="Last updated on Jun 18, 2024, 6:23 PM UTC (2894d16)">Diff</a>

Add a note to encoding guidance about table order in brotli patches.

---

Overview.bs
Overview.html

- updates to local bibliography
- format as WD not ED
- sadly, some manual edits to the generated HTML to make it pass pubrules
Longer term this should be fixed by updating the bikeshed boilerplate files
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/IFT/pull/189.html" title="Last updated on Jul 5, 2024, 5:49 PM UTC (c3946cd)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/IFT/189/a8d734d...c3946cd.html" title="Last updated on Jul 5, 2024, 5:49 PM UTC (c3946cd)">Diff</a>

Updates for publication as WD on 2024 07 09

---

Overview.bs
Overview.html

I've been working on implementing a format 1 patch map parser and in the process found some issues and areas that were underspecified. This makes some changes to address those:
- Explicitly allow the feature map offset to be null.
- Change entry count from u32 -> u16. All entry index fields in the remainder of the table are at most u16 so no need for this to be u32.
- Rename "entry count" to "max entry index": an entry count of 0 is always invalid (entry 0 always exists). So changing this to "max entry index" avoids that. Additionally allows entry indices up to the max of u16 to be used.
- Specifically mention that entry 0 should be ignored (used to mark glyphs already in the font).
- Specifically mention entry indices greater than max entry index are invalid.
- Note that not all entry …

Make Some Adjustments to Format 1 Patch Map

---

Overview.bs
Overview.html

1. Add a maximum height to each branch factor, this is the largest height needed to encode any 32 bit unsigned integer value for each branch factor.
2. In the decoding algorithm specify that values beyond the unicode maximum 0x10FFFF should be ignored.
The height maximum (above which the encoding will be rejected) is placed at 32 bits to allow room for any future changes to the unicode maximum, while allowing fonts using codepoints above 0x10FFFF to not be rejected by clients implementing this version of the standard.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/IFT/pull/191.html" title="Last updated on Jul 22, 2024, 9:28 PM UTC (70f91e2)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/IFT/191/a287147...70f91e2.html" title="Last updated on Jul 22, 2024, 9:28 PM UTC …

Add additional restrictions to sparse bit set to avoid decoding values outside of unicode.

---

Overview.bs
Overview.html

Based on experience of implementing format 2 parsing this adds some additional validation:
- Format number must be one of the valid formats
- URI template must be utf8
- design space start < end
- limit max numeric entry id to 32 bits.
- Move bias into the sparse bit set decoding algorithm so the max set value limit (unicode max 0x10FFFF) applies to the post bias values.
- Added some clarification on how to intersect design spaces.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/IFT/pull/203.html" title="Last updated on Aug 22, 2024, 7:41 PM UTC (5665f0d)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/IFT/203/78f986b...5665f0d.html" title="Last updated on Aug 22, 2024, 7:41 PM UTC (5665f0d)">Diff</a>

Add more Normative Validation rules for Format 2

---

Overview.bs
Overview.html

Updates the text to specify how to handle string ids for entries that don't set the optional entryIdStringLength field.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/IFT/pull/204.html" title="Last updated on Aug 27, 2024, 12:01 AM UTC (dcbd8a5)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/IFT/204/a80e684...dcbd8a5.html" title="Last updated on Aug 27, 2024, 12:01 AM UTC (dcbd8a5)">Diff</a>

Clarify how to handle format 2 string entry id's.

---

Overview.bs
Overview.html

This allows a conformat client implementation to optimize format 1 entry intersection by only checking the relevant parts of the table. See #198 for more context.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/IFT/pull/199.html" title="Last updated on Aug 27, 2024, 10:22 PM UTC (72967a4)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/IFT/199/06f2625...72967a4.html" title="Last updated on Aug 27, 2024, 10:22 PM UTC (72967a4)">Diff</a>

In format 1 ignore most invalid data instead of failing with an error.

---

Overview.bs
Overview.html

As discussed at the TPAC working group meeting this drops the "brotli" patch type because it is not expected to see wide use due to incompatibility with WOFF2 and mixed patch type encodings.
This leaves two remaining patch types:
- Table Keyed (renamed from the previous "per table brotli"): operates at the table level.
- Glyph Keyed: operates at the glyph level.
"Per table brotli" was renamed to "Table Keyed" to keep the naming of the patch formats consistent. The mention of brotli was dropped from the name since both glyph keyed and table keyed patches use brotli internally.
Fixes: #214
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/IFT/pull/217.html" title="Last updated on Sep 30, 2024, 10:10 PM UTC (0eab2f7)">Preview</a> | <a …

Remove the pure brotli patch type, rename remaining brotli patch type to "Table Keyed"

---

Overview.bs
Overview.html

Also some additional tweaks related to extension algorithm:
- In encoding considerations note a 4th technique for handling shared glyphs of using a separate patch with the common elements.
- Change "original font" to "initial font" in the extension algorithm.
- Reword the invalidation section to make it more focused on invalidation in the context of extension.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/IFT/pull/219.html" title="Last updated on Oct 3, 2024, 6:27 PM UTC (529de0e)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/IFT/219/926f033...529de0e.html" title="Last updated on Oct 3, 2024, 6:27 PM UTC (529de0e)">Diff</a>

Add summary of extension algorithm to extension intro section.

---

Overview.bs
Overview.html

- Make TablePatch/length into TablePatch/maxUncompressedLength and actually enforce it in the application algorithm.
- Clarify what happens when both bit 1 and 0 of flags are set, table removal takes priority.
- Make it an error for a non-replacement patch to be missing the base table in the source font.
- Make it an error to have leftover unused data in the brotliStream.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/IFT/pull/220.html" title="Last updated on Oct 7, 2024, 2:51 AM UTC (ac7d201)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/IFT/220/f088d8a...ac7d201.html" title="Last updated on Oct 7, 2024, 2:51 AM UTC (ac7d201)">Diff</a>

Tweaks to table keyed patches based on experience implementing it.

---

Overview.bs
Overview.html

Addresses some issues and ambiguities I  encountered while implementing glyph keyed patch parsing and application:
- Change brotli stream "length" field to be a max uncompressed length for consistency with table keyed patches.
- Add a note that glyph keyed patch application can only modify loca/glyf/gvar/CFF/CFF2.
- Require table tags and glyph id lists to be sorted and unique.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/IFT/pull/221.html" title="Last updated on Oct 19, 2024, 12:37 AM UTC (441a7fa)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/IFT/221/76b46d7...441a7fa.html" title="Last updated on Oct 19, 2024, 12:37 AM UTC (441a7fa)">Diff</a>

Various tweaks to Glyph Keyed format text

---

Overview.bs
Overview.html

Insted of checking code point by code point, greedily accumulate spans of text which do not have any matching unnapplied patches. Each span can be safely rendered in isolation, however substitution rules between spans will not work until font extension is complete for the shaping unit.
This works on the following assumptions:
- By encoder requirements, if we have a span of text with an associated subset definition and there are no unapplied patches matching that definition then that span of text can be rendered correctly in isolation.
- Then while a shaping unit as a whole is not ready we can still find spans within that unit which are ready.
Given that, we can then use a straightforward greedy approach where we incrementally increase a span until it fails the intersection check. This …

Add a more general readiness check for finding which parts within a shaping unit are supported.

---

Overview.bs
Overview.html

***
<a href="https://pr-preview.s3.amazonaws.com/w3c/IFT/pull/228.html" title="Last updated on Oct 30, 2024, 11:52 PM UTC (f282bf4)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/IFT/228/0d75a6c...f282bf4.html" title="Last updated on Oct 30, 2024, 11:52 PM UTC (f282bf4)">Diff</a>

Glyph Keyed: Move sorting requirement from tableCount to the array field.

---

Overview.bs
Overview.html

Missed in the previous PR, we also need to check that the font normally supports the code point by checking it is present in the cmap table.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/IFT/pull/229.html" title="Last updated on Oct 31, 2024, 12:02 AM UTC (44c2d97)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/IFT/229/0d75a6c...44c2d97.html" title="Last updated on Oct 31, 2024, 12:02 AM UTC (44c2d97)">Diff</a>

In the readiness check also check that cmap supports each codepoint.

---

Overview.bs
Overview.html

- Accidental swap of O with 0.
- Invalid template syntax {/+id64} changed to /{+id64}
- Added examples using numeric ids and id64 variable.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/IFT/pull/236.html" title="Last updated on Nov 14, 2024, 12:10 AM UTC (c35a328)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/IFT/236/3fda23d...c35a328.html" title="Last updated on Nov 14, 2024, 12:10 AM UTC (c35a328)">Diff</a>

Fix a couple of mistakes in the URI template examples.

---

Overview.bs
Overview.html

Fixes #234
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/IFT/pull/241.html" title="Last updated on Nov 21, 2024, 11:46 PM UTC (40de31e)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/IFT/241/1aa27d8...40de31e.html" title="Last updated on Nov 21, 2024, 11:46 PM UTC (40de31e)">Diff</a>

Consistently Use 'patch format' instead of 'patch encoding'.

---

Overview.bs
Overview.html

- In the algorithm steps add text saying the client can optionally start loads for any patches not invalidated by the current selection.
- Group patches by invalidation category prior to the selection step to improve clarity.
- Note that intersection doesn't need to be repeated on each iteration when only no invalidation patches are left.
Addresses #232, #233, and #239.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/IFT/pull/244.html" title="Last updated on Nov 22, 2024, 11:22 PM UTC (4f22026)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/IFT/244/65bf200...4f22026.html" title="Last updated on Nov 22, 2024, 11:22 PM UTC (4f22026)">Diff</a>

Update extension algorithm to include explicit prefetching.

---

Overview.bs
Overview.html

The example shows howed a mixed (table + glyph keyed) IFT font would typically be processed by a client.
For #216
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/IFT/pull/237.html" title="Last updated on Dec 3, 2024, 5:01 PM UTC (b918bb4)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/IFT/237/457cd10...b918bb4.html" title="Last updated on Dec 3, 2024, 5:01 PM UTC (b918bb4)">Diff</a>

Add appendix B which contains an example of the extension algorithm execution.

---

Overview.bs
Overview.html

- Clarify how id 0 during substitution is handled. Previously this was a bit ambiguous as the text stated to strip all 0 bytes.
- Specify that when applying templates the substitution may fail due to a malformed template.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/IFT/pull/249.html" title="Last updated on Jan 17, 2025, 6:52 PM UTC (b3183d6)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/IFT/249/de17c8b...b3183d6.html" title="Last updated on Jan 17, 2025, 6:52 PM UTC (b3183d6)">Diff</a>

Some clarifications around uri templates

---

Overview.bs
Overview.html

There was a WD status and a hardcoded date, so the spec always said:
> [W3C Working Draft](https://www.w3.org/standards/types#WD), 9 July 2024
Now it says ED, and the last edited date
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/IFT/pull/250.html" title="Last updated on Jan 19, 2025, 1:22 AM UTC (1d9d34f)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/IFT/250/6be6998...1d9d34f.html" title="Last updated on Jan 19, 2025, 1:22 AM UTC (1d9d34f)">Diff</a>

[editorial] back to ED, remove hardcoded date

---

Overview.bs
Overview.html

Instead of producing multiple subset definitions, define the intersection check in terms of whether referenced child entries would intersect. This largely provides the same functionality while overall making the mechanism simpler to reason about. Additionally it provides a path to a more efficient client side implementation, which can now cache the intersection checks on prior entries to quickly compute down stream entry intersection results. The prior approach requires in some cases fully expanding out the subset definition unions for each entry to correctly compute intersection results.
Also adds an appendix B example using child indices to demonstrate how UVS specific patches can be loaded. Fixes #245.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/IFT/pull/252.html" title="Last …

Rework the copy indices mechanism

---

Makefile
Overview.bs
Overview.html

Also fix some mismatched html tags.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/IFT/pull/261.html" title="Last updated on Mar 13, 2025, 6:07 PM UTC (6d363b9)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/IFT/261/f081fda...6d363b9.html" title="Last updated on Mar 13, 2025, 6:07 PM UTC (6d363b9)">Diff</a>

Fix the feature registry appendix which accidentally got replaced by an older version from the patch subset spec.

---

Overview.bs
Overview.html

Context: https://lists.w3.org/Archives/Public/public-webfonts-wg/2025Feb/0002.html
This makes so updates to the spec which allows mapping entries to list more than one URL, where all URLs after the first one are treated as preloads. This will allow table keyed patch graphs to utilize less patches by preloading additional jumps in the graph instead of requiring them to be placed into unique patches.
Three main areas are modified:
- Format 2: one bit from the id delta and length fields is reserved to indicate an additional value follows. This allows for encoding more than one value without increasing the cost of encoding entries with only one value.
- Extension algorithm: is updated to preload all URLs listed in the selected entry.
- Invalidating Selection Algorithm: prioritizes any entries …

Spec changes to allow entries to optionally include patch preload lists.

---

Overview.bs
Overview.html

Based on the discussion in #259:
- Stop using rfc3986 and instead use whatwg URL which supersedes rfc3986.
- Limit URL templates to level one operators, this will make it trivial for client implementations to implement template substitution and avoids needing to pull in a complete general purpose rfc6570 implementation.
- Clarify percent encoding always produces upper case letters.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/IFT/pull/263.html" title="Last updated on Mar 20, 2025, 8:04 PM UTC (57bd8f5)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/IFT/263/32f7e9c...57bd8f5.html" title="Last updated on Mar 20, 2025, 8:04 PM UTC (57bd8f5)">Diff</a>

Switch to WhatWG URL and Limit URL Templates to level 1

---

Overview.bs
Overview.html

- Specified to only be on the 'IFT ' table so it's not duplicated in fonts which also have an IFTX patchmap.
- Required to be present and accurate when font has CFF and/or CFF2.
For #260
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/IFT/pull/265.html" title="Last updated on Mar 31, 2025, 6:14 PM UTC (0ac20ee)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/IFT/265/af20875...0ac20ee.html" title="Last updated on Mar 31, 2025, 6:14 PM UTC (0ac20ee)">Diff</a>

For fonts with CFF or CFF2 tables add a field to the patch map with o

---

Overview.bs
Overview.html

This makes the patch map tables self contained so they can be parsed without outside knowledge about the presence or absence of CFF, CFF2 tables.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/IFT/pull/266.html" title="Last updated on Apr 3, 2025, 6:55 PM UTC (2e51ef9)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/IFT/266/cef27ab...2e51ef9.html" title="Last updated on Apr 3, 2025, 6:55 PM UTC (2e51ef9)">Diff</a>

Add flag bits to signal presence of optional charstring offsets.

---

Overview.bs
Overview.html

For #270 add a note which recommends the usage of WOFF2 with IFT fonts (with the usual caveat of avoiding glyf/loca transformations).
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/IFT/pull/271.html" title="Last updated on May 1, 2025, 12:13 AM UTC (48195fe)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/IFT/271/ca92138...48195fe.html" title="Last updated on May 1, 2025, 12:13 AM UTC (48195fe)">Diff</a>

Add a note to the font compression section recommending WOFF2.

---

Overview.bs
Overview.html

Add an additional step to generate the URL for that case. This makes the interpretation algorithm match the field descriptions.

In format 2 interpretation handling of an unspecified entry id delta/length was missing.

---

Overview.bs
Overview.html

Context: https://github.com/w3ctag/design-reviews/issues/1057#issuecomment-2859533716
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/IFT/pull/274.html" title="Last updated on May 14, 2025, 5:41 PM UTC (912ffa6)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/IFT/274/289e22f...912ffa6.html" title="Last updated on May 14, 2025, 5:41 PM UTC (912ffa6)">Diff</a>

Add a note about optimizing glyph keyed patch application when multiple patches are present.

---

Overview.bs
Overview.html

Since url templates is primarily a compression mechanism internal to the IFT tables there is no need for templates to be human readable. By switching to an opcode based approach we significantly simplify the template expansion process leading to simpler client implementations.
See: https://github.com/w3c/IFT/issues/259#issuecomment-2794840010 for context and more details.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/IFT/pull/281.html" title="Last updated on Jun 11, 2025, 6:42 PM UTC (03af9d4)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/IFT/281/6e79bc4...03af9d4.html" title="Last updated on Jun 11, 2025, 6:42 PM UTC (03af9d4)">Diff</a>

Drop rfc6570 uri templates, replace with opcode encoded template.

---

Overview.bs
Overview.html

First pass at providing guidance on how encoding choices affects the privacy characteristics of an IFT font. For #267.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/IFT/pull/282.html" title="Last updated on Jun 19, 2025, 7:26 PM UTC (79fa7ca)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/IFT/282/a81d6ca...79fa7ca.html" title="Last updated on Jun 19, 2025, 7:26 PM UTC (79fa7ca)">Diff</a>

Expand privacy section to provide guidance for encoders.

---

Overview.bs
Overview.html

The autogenerated html from Bikeshed did not pass pubrules so I edited the status section until it did.
I should make a pull request on the bikeshed boilerplate repo to fix that in a more robust way. 
This includes the text shaping definition link.
Meanwhile this document passes and will be published this week.
Approval:
https://github.com/w3c/transitions/issues/732#issuecomment-3117245240
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/IFT/pull/287.html" title="Last updated on Jul 28, 2025, 2:38 PM UTC (1eb1ec4)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/IFT/287/ee7741e...1eb1ec4.html" title="Last updated on Jul 28, 2025, 2:38 PM UTC (1eb1ec4)">Diff</a>

CR July 2025

---

Overview.bs

Remove conformance keywords (should) from 'Note:' in 4.6
