Makefile, Overview.bs, Overview.html, RangeRequest.bs, RangeRequest.html
Also adds specification for how to make an incxfer request in html.
=> Split range request into a separate document.

Overview.bs, Overview.html
=> Add shared brotli reference

Overview.bs, Overview.html
- Use 'must' for error response.
- Add requirement for patch subset servers to support range request.
=> Fixes for a couple issues:

Overview.bs, Overview.html
=> Reference simulation results that support a branch factor of 4.

Overview.bs, Overview.html
when a patch subset service is composed of multiple tasks.
Fixes #29
=> Add a note warning about the dangers of subsetter upgrades  

Overview.bs
I think I've found three typo-s. (please mark as non-substantive)
=> possible fixes

Overview.bs, Overview.html, RangeRequest.html
=> Make the link too fast hash a reference.

.pr-preview.json
Thank you for your work on this specification! I'm tracking the progress of this spec and hope it will improve page load time and make WebFonts more usable.
This PR adds [PR Preview](https://github.com/tobie/pr-preview) for the main spec. Although [PR Preview does not yet support multiple documents](https://github.com/tobie/pr-preview/issues/18), I think it is more convenient to have the preview and diff of the main document than no preview at all.
=> Add preview and diff to spec pull requests

RangeRequest.bs, RangeRequest.html
First draft of range request method
=> First draft of range request method

Overview.bs, Overview.html
Fixes #46
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/IFT/pull/65.html" title="Last updated on Dec 13, 2021, 6:31 PM UTC (29d5ed6)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/IFT/65/f1f7516...29d5ed6.html" title="Last updated on Dec 13, 2021, 6:31 PM UTC (29d5ed6)">Diff</a>
=> Swap out 'supports incremental' for tech(incremental).

Overview.bs, Overview.html, RangeRequest.html
Fixes #51
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/IFT/pull/66.html" title="Last updated on Dec 14, 2021, 12:15 AM UTC (2835001)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/IFT/66/e3aa303...2835001.html" title="Last updated on Dec 14, 2021, 12:15 AM UTC (2835001)">Diff</a>
=> Describe request in terms of fetch.

Overview.bs, Overview.html
Fixes #68
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/IFT/pull/71.html" title="Last updated on Dec 16, 2021, 12:12 AM UTC (d35348a)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/IFT/71/74851a9...d35348a.html" title="Last updated on Dec 16, 2021, 12:12 AM UTC (d35348a)">Diff</a>
=> Add a section on error handling in the client.

Overview.bs, Overview.html
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/IFT/pull/78.html" title="Last updated on Feb 10, 2022, 10:59 PM UTC (0c35cdc)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/IFT/78/d6780df...0c35cdc.html" title="Last updated on Feb 10, 2022, 10:59 PM UTC (0c35cdc)">Diff</a>
=> Add some clarifications in the sparse bit set section around encoding empty sets.

Overview.bs, Overview.html
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/IFT/pull/80.html" title="Last updated on Feb 28, 2022, 11:34 PM UTC (35b46b6)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/IFT/80/2657f86...35b46b6.html" title="Last updated on Feb 28, 2022, 11:34 PM UTC (35b46b6)">Diff</a>
=> Tag conformance statements around server response requirements.

Overview.bs, Overview.html
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/IFT/pull/88.html" title="Last updated on Apr 27, 2022, 6:35 PM UTC (f6317ee)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/IFT/88/94f2790...f6317ee.html" title="Last updated on Apr 27, 2022, 6:35 PM UTC (f6317ee)">Diff</a>
=> Add more conformance tags, notably adds tags relating to server handling of variable axes.

Overview.bs, Overview.html
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/IFT/pull/89.html" title="Last updated on Apr 28, 2022, 8:55 PM UTC (026f7c4)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/IFT/89/53f667e...026f7c4.html" title="Last updated on Apr 28, 2022, 8:55 PM UTC (026f7c4)">Diff</a>
=> Add conformance tags for AxisSpace/Interval requirements and font subset requirements.

Overview.bs, Overview.html
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/IFT/pull/96.html" title="Last updated on Jun 2, 2022, 2:08 PM UTC (25abf33)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/IFT/96/3ca3de5...25abf33.html" title="Last updated on Jun 2, 2022, 2:08 PM UTC (25abf33)">Diff</a>
=> One outline table, fix #82

Overview.bs, Overview.html
For #108 and #104.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/IFT/pull/112.html" title="Last updated on Jul 19, 2022, 12:00 AM UTC (66cb400)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/IFT/112/aa09c4d...66cb400.html" title="Last updated on Jul 19, 2022, 12:00 AM UTC (66cb400)">Diff</a>
=> Add "Performance Considerations" section.

Overview.bs, Overview.html
Fixes #94.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/IFT/pull/128.html" title="Last updated on Nov 9, 2022, 7:47 PM UTC (ad1339f)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/IFT/128/bc5b5fd...ad1339f.html" title="Last updated on Nov 9, 2022, 7:47 PM UTC (ad1339f)">Diff</a>
=> Add a note about how feature selection interacts with IFT method selection.

Overview.bs, Overview.html
Fixes #118.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/IFT/pull/133.html" title="Last updated on Nov 21, 2022, 6:40 PM UTC (1ba5f0c)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/IFT/133/7f5e82e...1ba5f0c.html" title="Last updated on Nov 21, 2022, 6:40 PM UTC (1ba5f0c)">Diff</a>
=> Expand section of reducing the number of network requests.

Makefile, Overview.bs, Overview.html, RangeRequest.bs, RangeRequest.html
This will allow the patch subset specification to be advanced without range request being complete.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/IFT/pull/138.html" title="Last updated on Mar 13, 2023, 9:49 PM UTC (62e7c51)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/IFT/138/b9697c9...62e7c51.html" title="Last updated on Mar 13, 2023, 9:49 PM UTC (62e7c51)">Diff</a>
=> Split off the range request section back into a separate document.

Overview.bs, Overview.html
The old text was not accurate aboute the purpose of checksums. Fixes #139
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/IFT/pull/142.html" title="Last updated on Mar 17, 2023, 9:51 PM UTC (04992f9)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/IFT/142/14340e1...04992f9.html" title="Last updated on Mar 17, 2023, 9:51 PM UTC (04992f9)">Diff</a>
=> Update privacy section on checksums.

Overview.bs, Overview.html, RangeRequest.bs, RangeRequest.html
Small updates to pass publication rules
Added the missing (and required) changes section, based on commit messages
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/IFT/pull/145.html" title="Last updated on May 26, 2023, 4:30 PM UTC (706a167)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/IFT/145/0fa6550...706a167.html" title="Last updated on May 26, 2023, 4:30 PM UTC (706a167)">Diff</a>
=> Changes for /TR publication

Overview.bs, Overview.html
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/IFT/pull/147.html" title="Last updated on Jun 15, 2023, 10:54 PM UTC (c27368e)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/IFT/147/bac9661...c27368e.html" title="Last updated on Jun 15, 2023, 10:54 PM UTC (c27368e)">Diff</a>
=> Recommend using unicode-range in incremental @font-face's

Overview.html
Forgot to rebuild Overview.html for changes in the last commit.
=> Update Overview.html to reflect changes in metadata.

Overview.bs
***
<a href="https://pr-preview.s3.amazonaws.com/skef/IFT/pull/158.html" title="Last updated on Feb 27, 2024, 11:30 PM UTC (12f1da2)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/IFT/158/6946e39...skef:12f1da2.html" title="Last updated on Feb 27, 2024, 11:30 PM UTC (12f1da2)">Diff</a>
=> Some editorial suggestions

Overview.bs
Some suggestions and additions for #171 . Note that this PR is against `reorg` rather than `main`. Seemed easiest to have the conversation this way.
***
<a href="https://pr-preview.s3.amazonaws.com/skef/IFT/pull/172.html" title="Last updated on Apr 30, 2024, 12:22 AM UTC (1981855)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/IFT/172/e81b57e...skef:1981855.html" title="Last updated on Apr 30, 2024, 12:22 AM UTC (1981855)">Diff</a>
=> Suggested reorg edits and additions

Overview.bs, Overview.html
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/IFT/pull/173.html" title="Last updated on May 14, 2024, 10:26 PM UTC (086c130)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/IFT/173/8ad7990...086c130.html" title="Last updated on May 14, 2024, 10:26 PM UTC (086c130)">Diff</a>
=> Add text for the privacy considerations section.

Overview.bs, Overview.html
Allow extension to optionally continue in the case of a failure to load a URL, otherwise recommend extension stop.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/IFT/pull/163.html" title="Last updated on May 23, 2024, 9:08 PM UTC (38d3371)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/IFT/163/062767e...38d3371.html" title="Last updated on May 23, 2024, 9:08 PM UTC (38d3371)">Diff</a>
=> Fill out the 'Handle errors' section.

Overview.bs, Overview.html
For #176
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/IFT/pull/181.html" title="Last updated on May 29, 2024, 11:56 PM UTC (4d37717)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/IFT/181/91c52b0...4d37717.html" title="Last updated on May 29, 2024, 11:56 PM UTC (4d37717)">Diff</a>
=> Tweaks to encoder section wording

Overview.bs, Overview.html
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/IFT/pull/186.html" title="Last updated on Jun 19, 2024, 5:08 PM UTC (22f8626)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/IFT/186/97c7aee...22f8626.html" title="Last updated on Jun 19, 2024, 5:08 PM UTC (22f8626)">Diff</a>
=> Add more guidance about network round trips + patch types.

Overview.bs, Overview.html
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/IFT/pull/188.html" title="Last updated on Jul 4, 2024, 8:16 PM UTC (d6026f6)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/IFT/188/024b91e...d6026f6.html" title="Last updated on Jul 4, 2024, 8:16 PM UTC (d6026f6)">Diff</a>
=> Note the encoding guidance is based on current best understanding of building a high quality encoder.

Overview.bs, Overview.html
Fixes #200
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/IFT/pull/202.html" title="Last updated on Aug 13, 2024, 9:50 PM UTC (d77a47e)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/IFT/202/2b99efa...d77a47e.html" title="Last updated on Aug 13, 2024, 9:50 PM UTC (d77a47e)">Diff</a>
=> Prefer 'code point' over 'codepoint'.

Overview.bs, Overview.html
Fixes #196
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/IFT/pull/205.html" title="Last updated on Aug 28, 2024, 4:52 PM UTC (bfc4e50)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/IFT/205/a8e3185...bfc4e50.html" title="Last updated on Aug 28, 2024, 4:52 PM UTC (bfc4e50)">Diff</a>
=> Add a small section explaining caching incremental fonts.

Overview.bs, Overview.html
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/IFT/pull/209.html" title="Last updated on Sep 18, 2024, 7:12 PM UTC (ba557a8)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/IFT/209/9bf5b78...ba557a8.html" title="Last updated on Sep 18, 2024, 7:12 PM UTC (ba557a8)">Diff</a>
=> Reword the offline usage section to make it clearer what the use case is for.

Overview.bs
As discussed at TPAC 2024
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/IFT/pull/215.html" title="Last updated on Sep 24, 2024, 5:32 PM UTC (b1f8a10)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/IFT/215/e5e18ae...b1f8a10.html" title="Last updated on Sep 24, 2024, 5:32 PM UTC (b1f8a10)">Diff</a>
=> Number Security, Privacy, Changes

Overview.bs, Overview.html
Fixes #211
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/IFT/pull/218.html" title="Last updated on Oct 1, 2024, 4:53 PM UTC (9831fcf)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/IFT/218/8e869e0...9831fcf.html" title="Last updated on Oct 1, 2024, 4:53 PM UTC (9831fcf)">Diff</a>
=> Generalize the section on WOFF2 + IFT section to any compression format.

Overview.bs, Overview.html
Fixes #212.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/IFT/pull/243.html" title="Last updated on Nov 22, 2024, 8:06 PM UTC (906eff7)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/IFT/243/c2bf1c2...906eff7.html" title="Last updated on Nov 22, 2024, 8:06 PM UTC (906eff7)">Diff</a>
=> Add example of using css supports to opt in to an incremental font.

Overview.bs
Uses the better abstract from 
https://docs.google.com/document/d/1MAuXOJr7FQevxTg9NhaBOB5Y45Ak9Ad3SRyKDfND8SY/edit?tab=t.0
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/IFT/pull/246.html" title="Last updated on Dec 9, 2024, 10:00 PM UTC (b578323)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/IFT/246/fe900b5...b578323.html" title="Last updated on Dec 9, 2024, 10:00 PM UTC (b578323)">Diff</a>
=> Better abstract #213

Overview.html
I updated the `.bs` but didn't regenerate the `.html`, d'oh
=> actually use the abstract in the spec

Overview.bs, Overview.html
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/IFT/pull/251.html" title="Last updated on Jan 31, 2025, 12:40 AM UTC (0229f16)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/IFT/251/69094a2...0229f16.html" title="Last updated on Jan 31, 2025, 12:40 AM UTC (0229f16)">Diff</a>
=> Update the changes section in preparation for a new working draft.

IFT-Explainer.md
Forgot that I had to run [doctoc](https://github.com/thlorenz/doctoc) to update the table of contents.
No other changes
=> [Explainer] Update TOC

Overview.bs, Overview.html
Boilerplate changes for WD
Updated list of changes
Fixed some links
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/IFT/pull/258.html" title="Last updated on Feb 17, 2025, 3:35 PM UTC (826a203)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/IFT/258/a573189...826a203.html" title="Last updated on Feb 17, 2025, 3:35 PM UTC (826a203)">Diff</a>
=> Changes for February Working Draft, #256

Overview.bs, Overview.html
As discussed in #260.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/IFT/pull/264.html" title="Last updated on Mar 19, 2025, 8:57 PM UTC (0855db2)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/IFT/264/40d37ef...0855db2.html" title="Last updated on Mar 19, 2025, 8:57 PM UTC (0855db2)">Diff</a>
=> Add CFF specific requirements for IFT

IFT-Explainer.md
See https://github.com/WebKit/standards-positions/issues/461#issuecomment-2786554104
=> [explainer] WebKit is now positive

Overview.bs
As mentioned on the call today
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/IFT/pull/269.html" title="Last updated on Apr 22, 2025, 4:49 PM UTC (c1a09bd)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/IFT/269/3275836...c1a09bd.html" title="Last updated on Apr 22, 2025, 4:49 PM UTC (c1a09bd)">Diff</a>
=> Update to (current) shared brotli 15, #101

Overview.bs, Overview.html
Fixes: #277
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/IFT/pull/279.html" title="Last updated on May 29, 2025, 10:56 PM UTC (3130121)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/IFT/279/69c78a8...3130121.html" title="Last updated on May 29, 2025, 10:56 PM UTC (3130121)">Diff</a>
=> Specify a selection/fetch ordering for non-invalidating patches.

Overview.bs, Overview.html
Fixes #276.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/IFT/pull/280.html" title="Last updated on Jun 5, 2025, 7:33 PM UTC (6706928)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/IFT/280/a2d65fe...6706928.html" title="Last updated on Jun 5, 2025, 7:33 PM UTC (6706928)">Diff</a>
=> [IFT] add more specific information on configuring the fetch request.

Overview.bs, Overview.html
In preparation for (hopefully final) working draft
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/IFT/pull/283.html" title="Last updated on Jul 8, 2025, 6:24 AM UTC (31211df)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/IFT/283/34cf8cf...31211df.html" title="Last updated on Jul 8, 2025, 6:24 AM UTC (31211df)">Diff</a>
=> [editorial] Updated changes since 20 Feb WD

Overview.bs, Overview.html
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/IFT/pull/286.html" title="Last updated on Jul 25, 2025, 3:22 PM UTC (6bf3582)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/IFT/286/163f1de...6bf3582.html" title="Last updated on Jul 25, 2025, 3:22 PM UTC (6bf3582)">Diff</a>
=> Link to definition of shaping; define and export term shaping unit #285
